### ISSUE TITLE
Table border option "html table style"

### ISSUE THREAD

**Issue by khushbu-capsitech** [actingoffice/ActingOffice.App.Dev#65]
Developer Remark:->
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 14">
<link id=Main-File rel=Main-File
href="file:///C:\Users\LENOVO~1\AppData\Local\Temp\OICE_702223BE-E781-4E00-AE8E-8467D2E0E0EA.0\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\LENOVO~1\AppData\Local\Temp\OICE_702223BE-E781-4E00-AE8E-8467D2E0E0EA.0\msohtmlclip1\01\clip_filelist.xml">

<style>

</style>
</head>

<body link="#1155CC" vlink="#1155CC">

I have   added bootstrap table classes, so developer can use them
--

</body>

</html>

**Comment by mukesh-capsitech** [comment]
I have added bootstrap table classes, so developer can use them
